apiVersion: apps/v1
kind: Deployment
metadata:
  name: outputstreaming-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: outputstreaming
  template:
    metadata:
      labels:
        app: outputstreaming
    spec:
      volumes:
        - name: kafka-storage
          persistentVolumeClaim:
            claimName: image-storage-pvc
      containers:
        - name: output-streaming
          image: thivu19/output-streaming:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
          # 1. Set the hostname and port directly
            - name: DB_HOST
              value: "postgres-svc" # The K8s Service name
            - name: DB_PORT
              value: "5432"
          # 2. Get the DB name from your ConfigMap
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-configmap # The ConfigMap you already made
                  key: POSTGRES_DB
          # 3. Get the User and Password from your Secret
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret # The Secret you already made
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD  
            - name: POD_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: kafka-storage
              mountPath: /data/output