apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: outputstreaming-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: outputstreaming.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: outputstreaming-service
            port:
              number: 8080
