apiVersion: v1
kind: Service
metadata:
  name: outputstreaming-service
spec:
  selector:
    app: outputstreaming
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP